#!/usr/bin/env bash

gitclonecd() {
  git clone "$1" || return 1
  dir="$(basename "$1" .git)"
  echo "$dir"
  cd "$dir" || return 1
}
gitclonecd

# if [[ "$1" != ]]
#
#
#
# gitclonecd() {
#     git clone "$1" || return 1
#     dir=$(basename "$1")
#     dir="${dir%.git}"
#     echo "→ cd into $dir"
#     cd "$dir" || return 1
# }
